#!/bin/bash

##############################
#检测Make安装方式Apache的安装目录
##############################
updatedb

ENV_PATH=../env_config

CONF_PATH=`locate  httpd.conf |  grep "\/httpd.conf$" |  grep -v  "/etc/httpd/conf/httpd.conf"`

DOCUMENT_PATH=`grep  -i  "ServerRoot "   $CONF_PATH  | grep -v "^#" |  awk   '{print  $2}'`

LINE_NUM=`grep  -n  "Make_Installation_Directory"   $ENV_PATH  |  awk -F:  '{print $1}'`

#在"Make_Installation_Directory"行之后添加一行

sed  -ie  "/Make_Installation_Directory/a \'Make_Installation_Directory\':\'$DOCUMENT_PATH\'"   $ENV_PATH

#删除原来的"Make_Installation_Directory"行

sed -i  ''$LINE_NUM'd'   $ENV_PATH
