#!/bin/bash

##############################
#检测RPM安装方式的php主配置文件（php.ini和php-fpm.conf）的备份
##############################

[ `rpm -q php` ] || exit 1

updatedb

ENV_PATH=../env_config

#判断是否存在"CONF_BACK"目录

if  [ -d   CONF_BACK  ]
then	
	
else
	mkdir  ./CONF_BACK
if

\cp   /etc/php.ini     ./CONF_BACK
\cp   /etc/php-fpm.conf ./CONF_BACK
